[pytest]
addopts = -q --disable-warnings
markers =
    ui: tests ui (selenium)
    api: tests api (requests)
    slow: dlugie testy
    serial: testy niewykonywane rownolegle
    containers: testy z testcontainers (wymaga Dockera)

rp_endpoint = https://demo.reportportal.io
rp_api_key = ###
rp_project = default_personal